spring.application.name=ApiEnfermeria
server.servlet.context-path=/enfermeriaDR
server.port=8080
logging.level.org.springframework.web=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/SistemaDistritoRiego
spring.datasource.username=adminDR
spring.datasource.password=Leonardo123