spring.application.name=PersistenciaEnfermeria
spring.datasource.url=jdbc:postgresql://localhost:5432/SistemaDistritoRiego
spring.datasource.username=adminDR
spring.datasource.password=Leonardo123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect